exp_name: dare_qnn_next
seed: 777
device: cuda
deterministic: true
amp: none
use_compile: false
data:
  train_path: /home/biyotteu/dev/toss_v5/data/train.parquet
  test_path: /home/biyotteu/dev/toss_v5/data/test.parquet
  cache_dir: ./cache/dare_qnn
  use_cache: true
  chunked_build: true
  shard_rows: 2000000
  add_isna_mask: true
  impute_strategy: median
  cat_cols:
  - gender
  - age_group
  - inventory_id
  - day_of_week
  - hour
  - l_feat_1
  - l_feat_2
  - l_feat_3
  - l_feat_4
  - l_feat_5
  - l_feat_6
  - l_feat_7
  - l_feat_8
  - l_feat_9
  - l_feat_10
  - l_feat_11
  - l_feat_12
  - l_feat_13
  - l_feat_14
  - l_feat_15
  - l_feat_16
  - l_feat_17
  - l_feat_18
  - l_feat_19
  - l_feat_20
  - l_feat_21
  - l_feat_22
  - l_feat_23
  - l_feat_24
  - l_feat_25
  - l_feat_26
  - l_feat_27
  - feat_a_2
  - feat_a_8
  - feat_a_9
  num_cols_explicit:
  - feat_e_1
  - feat_e_2
  - feat_e_3
  - feat_e_4
  - feat_e_5
  - feat_e_6
  - feat_e_7
  - feat_e_8
  - feat_e_9
  - feat_e_10
  - feat_d_1
  - feat_d_2
  - feat_d_3
  - feat_d_4
  - feat_d_5
  - feat_d_6
  - feat_c_1
  - feat_c_2
  - feat_c_3
  - feat_c_4
  - feat_c_5
  - feat_c_6
  - feat_c_7
  - feat_c_8
  - feat_b_1
  - feat_b_2
  - feat_b_3
  - feat_b_4
  - feat_b_5
  - feat_b_6
  - feat_a_1
  - feat_a_3
  - feat_a_4
  - feat_a_5
  - feat_a_6
  - feat_a_7
  - feat_a_10
  - feat_a_11
  - feat_a_12
  - feat_a_13
  - feat_a_14
  - feat_a_15
  - feat_a_16
  - feat_a_17
  - feat_a_18
  - history_a_1
  - history_a_2
  - history_a_3
  - history_a_4
  - history_a_5
  - history_a_6
  - history_a_7
  - history_b_1
  - history_b_2
  - history_b_3
  - history_b_4
  - history_b_5
  - history_b_6
  - history_b_7
  - history_b_8
  - history_b_9
  - history_b_10
  - history_b_11
  - history_b_12
  - history_b_13
  - history_b_14
  - history_b_15
  - history_b_16
  - history_b_17
  - history_b_18
  - history_b_19
  - history_b_20
  - history_b_21
  - history_b_22
  - history_b_23
  - history_b_24
  - history_b_25
  - history_b_26
  - history_b_27
  - history_b_28
  - history_b_29
  - history_b_30
  hash_buckets:
    gender: 1005
    age_group: 1011
    day_of_week: 1009
    hour: 1026
    inventory_id: 1020
    l_feat_1: 1004
    l_feat_2: 1005
    l_feat_3: 1005
    l_feat_4: 1028
    l_feat_5: 2078
    l_feat_6: 1902
    l_feat_7: 1315
    l_feat_8: 1005
    l_feat_9: 1478
    l_feat_10: 1264
    l_feat_11: 2526
    l_feat_12: 6052
    l_feat_13: 1004
    l_feat_14: 4239
    l_feat_15: 3584
    l_feat_16: 1004
    l_feat_17: 1478
    l_feat_18: 1010
    l_feat_19: 1005
    l_feat_20: 1004
    l_feat_21: 1005
    l_feat_22: 1005
    l_feat_23: 1004
    l_feat_24: 1005
    l_feat_25: 2790
    l_feat_26: 1020
    l_feat_27: 1007
    feat_a_2: 1008
    feat_a_8: 1010
    feat_a_9: 1012
  num_patterns:
  - feat_*
  - history_*
  - l_feat_*
  manifest_train: ./cache/dare_qnn/train/manifest.json
  manifest_test: ./cache/dare_qnn/test/manifest.json
sequence:
  col: seq
  max_len: 400
  pad_id: 0
  top_k: 60
  recency_tau: 512
  query_mode: concat
  query_key: inventory_id
  transformer_block: true
  tfm:
    n_layers: 3
    n_heads: 8
    mha_dropout: 0.1
    ffn_hidden: 384
    ffn_dropout: 0.1
    norm: rms
    gating: softmax
    add_positional_bias: true
model:
  emb_dim: 64
  dare_dropout: 0.2
  cat_embedding_dims:
    gender: 8
    age_group: 8
    day_of_week: 8
    hour: 8
    inventory_id: 16
    l_feat_1: 8
    l_feat_2: 8
    l_feat_3: 8
    l_feat_4: 8
    l_feat_5: 33
    l_feat_6: 30
    l_feat_7: 18
    l_feat_8: 8
    l_feat_9: 22
    l_feat_10: 17
    l_feat_11: 40
    l_feat_12: 64
    l_feat_13: 8
    l_feat_14: 57
    l_feat_15: 51
    l_feat_16: 8
    l_feat_17: 22
    l_feat_18: 8
    l_feat_19: 8
    l_feat_20: 8
    l_feat_21: 8
    l_feat_22: 8
    l_feat_23: 8
    l_feat_24: 8
    l_feat_25: 43
    l_feat_26: 8
    l_feat_27: 8
    feat_a_2: 8
    feat_a_8: 8
    feat_a_9: 8
  qnn_alpha:
    enabled: true
    feature_embed_dim: 32
    heads: 6
    rank: 16
    proj_dim: 192
    mlp_hidden:
    - 512
    - 256
    dropout: 0.2
    use_se: true
    se_reduction: 8
    use_residual: true
    norm: rms
    pair_grouping: all
    aux_head_weight: 0.1
train:
  batch_size: 8192
  epochs: 8
  optimizer: adamw
  lr: 0.0003
  weight_decay: 0.0001
  warmup_epochs: 2
  cosine: true
  early_stop_patience: 3
  grad_clip_norm: 0.5
  monitor: score
cv:
  n_splits: 5
  group_key: inventory_id
  stratify_target: clicked
  time_key: day_of_week
  composite_group: true
eval:
  monitor: score
  maximize: true
calibration:
  enabled: true
  method: temperature
  lr: 0.05
  iters: 200
logging:
  log_dir: ./runs
  tb: true
  csv_log: true
  verbose_steps: 100
ensemble:
  method: logit_mean
  trim_ratio: 0.2
  weights: []
  val_weight_temperature: 10.0
sampler:
  type: None # balanced
  pos_fraction: 0.5
ema:
  enabled: true
  decay: 0.999
  eval_with_ema: true
  start_epoch: 1
